Category.create({id: 50, name: 'Alimentos, Bebidas y Tabaco'}, without_protection: true)
Category.create({id: 15, name: 'Combustibles, Aditivos para combustibles, Lubricantes y Materiales Anticorrosivos'}, without_protection: true)
Category.create({id: 31, name: 'Componentes y Suministros de Fabricacion'}, without_protection: true)
Category.create({id: 30, name: 'Componentes y Suministros de Fabricacion, Estructuras, Obras y Construcciones'}, without_protection: true)
Category.create({id: 32, name: 'Componentes y Suministros Electrónicos'}, without_protection: true)
Category.create({id: 95, name: 'CSS-MINSA'}, without_protection: true)
Category.create({id: 41, name: 'Equipo de Laboratorio, Medida, Observación y Comprobación'}, without_protection: true)
Category.create({id: 45, name: 'Equipo y Suministros de Imprenta, Fotográficos y Audiovisuales'}, without_protection: true)
Category.create({id: 47, name: 'Equipo y Suministros de limpieza'}, without_protection: true)
Category.create({id: 44, name: 'Equipo, Accesorios y Suministros de Oficina'}, without_protection: true)
Category.create({id: 42, name: 'Equipo, Accesorios y Suministros Médicos'}, without_protection: true)
Category.create({id: 46, name: 'Equipos y Suministros de Defensa, Orden Público, Protección y Seguridad'}, without_protection: true)
Category.create({id: 49, name: 'Equipos, suministros y accesorios deportivos y recreativos'}, without_protection: true)
Category.create({id: 27, name: 'Herramientas y Maquinaria en General'}, without_protection: true)
Category.create({id: 60, name: 'Instrumentos musicales, juegos, juguetes, artesanía y equipamiento, material, accesorios y suministros para educación'}, without_protection: true)
Category.create({id: 20, name: 'Maquinaria de minería y perforación de pozos y accesorios'}, without_protection: true)
Category.create({id: 23, name: 'Maquinaria y Accesorios de Fabricación y Transformación Industrial'}, without_protection: true)
Category.create({id: 21, name: 'Maquinaria y Accesorios para Agricultura, Pesca, Silvicultura y Fauna.'}, without_protection: true)
Category.create({id: 22, name: 'Maquinaria y Accesorios para Construcción y Edificación'}, without_protection: true)
Category.create({id: 26, name: 'Maquinaria y Accesorios para Generación y Distribución de Energía'}, without_protection: true)
Category.create({id: 24, name: 'Maquinaria, Accesorios y Suministros para Manejo, Acondicionamiento y Almacenamiento de Materiales'}, without_protection: true)
Category.create({id: 48, name: 'Maquinaria, Equipo y Suministros para la Industria de Servicios'}, without_protection: true)
Category.create({id: 10, name: 'Material, Accesorios y Suministros de Plantas y Animales Vivos'}, without_protection: true)
Category.create({id: 11, name: 'Materiales de Minerales y Tejidos y de Plantas y Animales no Comestibles'}, without_protection: true)
Category.create({id: 14, name: 'Materiales y Productos de Papel'}, without_protection: true)
Category.create({id: 51, name: 'Medicamentos y Productos Farmacéuticos'}, without_protection: true)
Category.create({id: 56, name: 'Muebles y mobiliario'}, without_protection: true)
Category.create({id: 52, name: 'Muebles, Accesorios, Electrodomésticos y Productos Electrónicos de Consumo'}, without_protection: true)
Category.create({id: 94, name: 'Organizaciones y Clubes'}, without_protection: true)
Category.create({id: 54, name: 'Productos para Relojería, Joyería y Gemas'}, without_protection: true)
Category.create({id: 55, name: 'Productos Publicados'}, without_protection: true)
Category.create({id: 12, name: 'Productos químicos incluyendo los bio-químicos y gases industriales'}, without_protection: true)
Category.create({id: 13, name: 'Resina y Colofonia y Caucho y Espuma y Película y Materiales Elastoméricos'}, without_protection: true)
Category.create({id: 53, name: 'Ropa, Maletas y Productos de Aseo Personal'}, without_protection: true)
Category.create({id: 81, name: 'Servicios basados en ingeniería, investigación y tecnología'}, without_protection: true)
Category.create({id: 72, name: 'Servicios de Construcción y Mantenimiento'}, without_protection: true)
Category.create({id: 70, name: 'Servicios de Contratación Agrícola, Pesquera, Forestal y de Fauna'}, without_protection: true)
Category.create({id: 92, name: 'Servicios de Defensa Nacional, Orden Público y Seguridad'}, without_protection: true)
Category.create({id: 80, name: 'Servicios de Gestión, Profesionales de Empresa y Administrativos'}, without_protection: true)
Category.create({id: 76, name: 'Servicios de Limpieza Industrial'}, without_protection: true)
Category.create({id: 71, name: 'Servicios de Perforación de Minería, Petróleo y Gas'}, without_protection: true)
Category.create({id: 73, name: 'Servicios de Producción y Fabricación Industrial'}, without_protection: true)
Category.create({id: 78, name: 'Servicios de Transporte, Almacenaje y Correo'}, without_protection: true)
Category.create({id: 90, name: 'Servicios de Viajes, Alimentación, Alojamiento y Entretenimiento'}, without_protection: true)
Category.create({id: 82, name: 'Servicios Editoriales, de Diseño, Gráficos y de Bellas Artes'}, without_protection: true)
Category.create({id: 86, name: 'Servicios Educativos y de Formación'}, without_protection: true)
Category.create({id: 84, name: 'Servicios Financieros y de Seguros'}, without_protection: true)
Category.create({id: 77, name: 'Servicios Medioambientales'}, without_protection: true)
Category.create({id: 91, name: 'Servicios Personales y Domésticos'}, without_protection: true)
Category.create({id: 93, name: 'Servicios Políticos y de Asuntos Cívicos'}, without_protection: true)
Category.create({id: 83, name: 'Servicios Públicos y Servicios Relacionados con el Sector Público'}, without_protection: true)
Category.create({id: 85, name: 'Servicios Sanitarios'}, without_protection: true)
Category.create({id: 40, name: 'Sistemas, Equipos y Componentes de Distribución y Acondicionamiento'}, without_protection: true)
Category.create({id: 39, name: 'Suministros, componentes y accesorios eléctricos y de iluminación'}, without_protection: true)
Category.create({id: 43, name: 'Telecomunicaciones y radiodifusión de tecnología de la información'}, without_protection: true)
Category.create({id: 25, name: 'Vehículos Comerciales, Militares y Particulares, Accesorios y Component'}, without_protection: true)
